### ISSUE TITLE
ubuntu 14.04 下运行错误

### ISSUE THREAD

**Issue by charli2014** [xiahei/Daily_scripts#3]
很实用的代码，但是我在ubuntu14.04下运行有些问题，依赖已经按照说明安装好了，但是还是有问题。

运行`baidu.py`，错误提示：

```
登录成功!
Traceback (most recent call last):
  File "baidu.py", line 124, in <module>
    start(usrname, pswd)
  File "baidu.py", line 114, in start
    tieba.markAllLikes(res)
  File "baidu.py", line 99, in markAllLikes
    print(kw+' '+status)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

运行`baidu_server.py`，没有任何提示，且签到失败。

**Comment by x1ah** [comment]
@charli2014 您的 Python 版本是？在我这运行是没有发生编码错误的。`baidu_server.py`是之前在服务器上跑的，需要在代码里填上自己的账号密码再运行。再尝试 `git pull` 更新一下再试试呢？

**Comment by charli2014** [comment]
@xiahei 是的，我都是在vps上跑的。
python是2.7版本的，但我也在python3上试了下，都有问题的，python3提示的是编码问题。
依赖都安装了的。
作者你是用的什么系统，centos吗

**Comment by x1ah** [comment]
@charli2014 我也是Ubuntu14.04，在 Python2 ，Python3 ，Windows 都测试过了，都没有出现编码问题。您pull了更新了吗？如果还不行在导入模块行添加：

``` python
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by charli2014** [comment]
刚刚已经重新拉下来过了，还是有问题，好奇怪。。。
`baidu.py`还是提示：

```
登录成功!
Traceback (most recent call last):
  File "baidu.py", line 122, in <module>
    start(usrname, pswd)
  File "baidu.py", line 112, in start
    tieba.markAllLikes(res)
  File "baidu.py", line 96, in markAllLikes
    print(kw + ' ' + status)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

`baidu_server.py`签到成功，但还是编码问题：

```
root@example:~/Daily_scripts/Baidu# python baidu_server.py
login succeed!
Thu Jun 30 10:52:50 2016 - 891873445 Traceback (most recent call last):
  File "baidu_server.py", line 108, in <module>
    print time.ctime(), '-', usrname, u'失败'
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

附上环境：

```
Ubuntu 14.04.4 LTS (GNU/Linux 2.6.32-042stab094.8 x86_64)
Linux example 2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux
```

能够签到成功，非常感谢！

**Comment by x1ah** [comment]
@charli2014 不太清楚您那到底是什么原因，之前说的万不得已的情况下添加

``` python
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

不知道有没有解决这个编码错误？

**Comment by charli2014** [comment]
应该是我的环境问题，加入

```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

还是这样。

**Comment by x1ah** [comment]
@charli2014 估计是我代码编码问题没能处理好，回头我再改改，暂时解决办法大概就是把输出给注释了，或者替换成别的，这么就大概不会编码错误了吧。感谢回馈！

**Comment by charli2014** [comment]
找到解决方法了。
我把带中文输出命令前面的'u'删掉后，就变的正常了。
像这样：

```
print u'共{0}个吧'.format(len(levels))
```

改成

```
print '共{0}个吧'.format(len(levels))
```

可能跟我本身系统就是中文有关系吧，python2的编码问题好复杂。。。。。
